version: "2.2"
services:
  webserver:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  dbserver:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=ciao

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1